services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    container_name: server
    depends_on:
      - postgres-db
      - cache-server-redis
    volumes:
      - ./server/upload:/server/upload
      - ./server/src:/server/src
      - .env.server:/server/.env
    networks:
      - tfd-network
  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    container_name: client
    depends_on:
      - server
    ports:
      - "${CLIENT_PORT}:8000"
    volumes:
      - .env.client:/app/.env
    networks:
      - tfd-network
  admin:
    build:
      context: .
      dockerfile: Dockerfile-admin
    container_name: admin
    depends_on:
      - server
    ports:
      - "${ADMIN_PORT}:5000"
    volumes:
      - .env.admin:/app/.env
    networks:
      - tfd-network
  nginx-load-balancer:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: nginx-load-balancer
    depends_on:
      - server
    environment:
      - NGINX_SERVER_NAME=localhost
      - HOST_1=server
      # - HOST_2=tfd-elearning-platform-server-2
      # - HOST_3=tfd-elearning-platform-server-3
      - PORT=3000
      - NGINX_MAX_BODY=100M
    ports:
      - "${API_PORT}:80"
    networks:
      - tfd-network
  postgres-db:
    image: postgres:14.12
    container_name: ${DB_HOST}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - tfdb:/var/lib/tfdb
    networks:
      - tfd-network
  cache-server-redis:
    image: redis:5
    container_name: cache-server-redis
    networks:
      - tfd-network
volumes:
  tfdb:
networks:
  tfd-network:
    driver: bridge
